### ISSUE TITLE
Mapa mental Heidi

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Heidi-19#1]

**Comment by Heidi-19** [comment]
[Mapa Mental-Heidi Lucy Bautista Sanjuan 6USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Heidi-19/files/10689734/Mapa.Mental-Heidi.Lucy.Bautista.Sanjuan.6USC.pdf)

**Comment by mel-16** [comment]
20% MUY BIEN

**Comment by josealfredo79** [comment]
Bien hecho..
